### ISSUE TITLE
如何生成RGB融合图像？

### ISSUE THREAD

**Issue by Liu-zhi-chao** [QiaoLiuHit/STFNet#1]
非常感谢您的这篇工作！请问如何生成一个具有色彩信息的融合图像呢？现在生成的图像都是灰度图，需要重新训练吗？

**Comment by QiaoLiuHit** [comment]
> 非常感谢您的这篇工作！请问如何生成一个具有色彩信息的融合图像呢？现在生成的图像都是灰度图，需要重新训练吗？

可以将RGB转成YCbCr，灰度图类似这里的Y, 保留CbCr，将融合后的灰度图结合这里的CbCr转回到RGB空间。
